-- Canteen Management System
-- Core relational schema derived from the Django models and migrations.
-- Target dialect: PostgreSQL
-- Scope: business/domain tables used in the project ERD
-- Note: Django framework tables such as sessions, admin logs, and
-- auth/content-type metadata are intentionally omitted from this ERD schema.

BEGIN;

CREATE TABLE IF NOT EXISTS accounts_customuser (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    password VARCHAR(128) NOT NULL,
    last_login TIMESTAMPTZ NULL,
    is_superuser BOOLEAN NOT NULL DEFAULT FALSE,
    username VARCHAR(150) NOT NULL,
    first_name VARCHAR(150) NOT NULL,
    last_name VARCHAR(150) NOT NULL,
    email VARCHAR(254) NOT NULL,
    is_staff BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    date_joined TIMESTAMPTZ NOT NULL,
    user_code VARCHAR(5) NOT NULL,
    role VARCHAR(20) NOT NULL,
    CONSTRAINT accounts_customuser_username_key UNIQUE (username),
    CONSTRAINT accounts_customuser_user_code_key UNIQUE (user_code),
    CONSTRAINT accounts_customuser_valid_role
        CHECK (role IN ('admin', 'student', 'teacher')),
    CONSTRAINT accounts_customuser_valid_user_code
        CHECK (user_code ~ '^[0-9]{5}$')
);

CREATE TABLE IF NOT EXISTS inventory_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_name VARCHAR(100) NOT NULL,
    category VARCHAR(50) NOT NULL,
    price NUMERIC(6, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    food_image VARCHAR(100) NULL,
    is_available BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT inventory_inventory_valid_category
        CHECK (
            category IN (
                'main_course',
                'snacks',
                'beverages',
                'desserts',
                'other'
            )
        ),
    CONSTRAINT inventory_inventory_nonnegative_price CHECK (price >= 0),
    CONSTRAINT inventory_inventory_nonnegative_quantity CHECK (quantity >= 0)
);

CREATE TABLE IF NOT EXISTS orders_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    order_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_amount NUMERIC(8, 2) NOT NULL,
    is_paid BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT orders_order_nonnegative_total CHECK (total_amount >= 0),
    CONSTRAINT orders_order_user_id_fk
        FOREIGN KEY (user_id)
        REFERENCES accounts_customuser (id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS orders_orderitem (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    price_at_purchase NUMERIC(6, 2) NOT NULL,
    CONSTRAINT orders_orderitem_positive_quantity CHECK (quantity > 0),
    CONSTRAINT orders_orderitem_nonnegative_price CHECK (price_at_purchase >= 0),
    CONSTRAINT orders_orderitem_order_id_fk
        FOREIGN KEY (order_id)
        REFERENCES orders_order (id)
        ON DELETE CASCADE,
    CONSTRAINT orders_orderitem_item_id_fk
        FOREIGN KEY (item_id)
        REFERENCES inventory_inventory (id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS payments_payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    payment_method VARCHAR(10) NOT NULL DEFAULT 'CASH',
    amount_paid NUMERIC(8, 2) NOT NULL,
    payment_time TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payments_payment_order_id_key UNIQUE (order_id),
    CONSTRAINT payments_payment_nonnegative_amount CHECK (amount_paid >= 0),
    CONSTRAINT payments_payment_order_id_fk
        FOREIGN KEY (order_id)
        REFERENCES orders_order (id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS payments_receipt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT payments_receipt_order_id_key UNIQUE (order_id),
    CONSTRAINT payments_receipt_order_id_fk
        FOREIGN KEY (order_id)
        REFERENCES orders_order (id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS orders_order_user_id_idx
    ON orders_order (user_id);

CREATE INDEX IF NOT EXISTS orders_orderitem_order_id_idx
    ON orders_orderitem (order_id);

CREATE INDEX IF NOT EXISTS orders_orderitem_item_id_idx
    ON orders_orderitem (item_id);

COMMENT ON TABLE accounts_customuser IS
'Application users: admins, students, and teachers.';

COMMENT ON TABLE inventory_inventory IS
'Menu and stock records managed by the canteen.';

COMMENT ON TABLE orders_order IS
'Order header table. One user can place many orders.';

COMMENT ON TABLE orders_orderitem IS
'Order line items. One order can contain many inventory items.';

COMMENT ON TABLE payments_payment IS
'One-to-one payment record for each paid order.';

COMMENT ON TABLE payments_receipt IS
'One-to-one receipt record generated for an order.';

COMMIT;
