# Generated by Django 5.2.11 on 2026-03-11 14:49

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_backfill_invalid_user_codes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={},
        ),
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", accounts.models.CustomUserManager()),
            ],
        ),
    ]
