# Generated by Django 5.2.11 on 2026-02-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('main_course', 'Main Course'), ('snacks', 'Snacks'), ('beverages', 'Beverages'), ('desserts', 'Desserts'), ('other', 'Other')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.PositiveBigIntegerField()),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='inventory_images/')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
    ]
